# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.20.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.20.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mpiekenbrock/tallem

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mpiekenbrock/tallem

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.20.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.20.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.20.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.20.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.20.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.20.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.20.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.20.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mpiekenbrock/tallem/CMakeFiles /Users/mpiekenbrock/tallem//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mpiekenbrock/tallem/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fast_svd

# Build rule for target.
fast_svd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fast_svd
.PHONY : fast_svd

# fast build rule for target.
fast_svd/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_svd.dir/build.make CMakeFiles/fast_svd.dir/build
.PHONY : fast_svd/fast

#=============================================================================
# Target rules for targets named carma_svd

# Build rule for target.
carma_svd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 carma_svd
.PHONY : carma_svd

# fast build rule for target.
carma_svd/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/carma_svd.dir/build.make CMakeFiles/carma_svd.dir/build
.PHONY : carma_svd/fast

# target to build an object file
cmake_pch.hxx.pch:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/carma_svd.dir/build.make CMakeFiles/carma_svd.dir/cmake_pch.hxx.pch
.PHONY : cmake_pch.hxx.pch

# target to preprocess a source file
cmake_pch.hxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/carma_svd.dir/build.make CMakeFiles/carma_svd.dir/cmake_pch.hxx.i
.PHONY : cmake_pch.hxx.i

# target to generate assembly for a file
cmake_pch.hxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/carma_svd.dir/build.make CMakeFiles/carma_svd.dir/cmake_pch.hxx.s
.PHONY : cmake_pch.hxx.s

src/tallem/carma_svd.o: src/tallem/carma_svd.cpp.o
.PHONY : src/tallem/carma_svd.o

# target to build an object file
src/tallem/carma_svd.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/carma_svd.dir/build.make CMakeFiles/carma_svd.dir/src/tallem/carma_svd.cpp.o
.PHONY : src/tallem/carma_svd.cpp.o

src/tallem/carma_svd.i: src/tallem/carma_svd.cpp.i
.PHONY : src/tallem/carma_svd.i

# target to preprocess a source file
src/tallem/carma_svd.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/carma_svd.dir/build.make CMakeFiles/carma_svd.dir/src/tallem/carma_svd.cpp.i
.PHONY : src/tallem/carma_svd.cpp.i

src/tallem/carma_svd.s: src/tallem/carma_svd.cpp.s
.PHONY : src/tallem/carma_svd.s

# target to generate assembly for a file
src/tallem/carma_svd.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/carma_svd.dir/build.make CMakeFiles/carma_svd.dir/src/tallem/carma_svd.cpp.s
.PHONY : src/tallem/carma_svd.cpp.s

src/tallem/fast_svd.o: src/tallem/fast_svd.cpp.o
.PHONY : src/tallem/fast_svd.o

# target to build an object file
src/tallem/fast_svd.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_svd.dir/build.make CMakeFiles/fast_svd.dir/src/tallem/fast_svd.cpp.o
.PHONY : src/tallem/fast_svd.cpp.o

src/tallem/fast_svd.i: src/tallem/fast_svd.cpp.i
.PHONY : src/tallem/fast_svd.i

# target to preprocess a source file
src/tallem/fast_svd.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_svd.dir/build.make CMakeFiles/fast_svd.dir/src/tallem/fast_svd.cpp.i
.PHONY : src/tallem/fast_svd.cpp.i

src/tallem/fast_svd.s: src/tallem/fast_svd.cpp.s
.PHONY : src/tallem/fast_svd.s

# target to generate assembly for a file
src/tallem/fast_svd.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_svd.dir/build.make CMakeFiles/fast_svd.dir/src/tallem/fast_svd.cpp.s
.PHONY : src/tallem/fast_svd.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... carma_svd"
	@echo "... fast_svd"
	@echo "... cmake_pch.hxx.pch"
	@echo "... cmake_pch.hxx.i"
	@echo "... cmake_pch.hxx.s"
	@echo "... src/tallem/carma_svd.o"
	@echo "... src/tallem/carma_svd.i"
	@echo "... src/tallem/carma_svd.s"
	@echo "... src/tallem/fast_svd.o"
	@echo "... src/tallem/fast_svd.i"
	@echo "... src/tallem/fast_svd.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

