[options]
python_requires = ">=3.9.1"

[tool.poetry]
name = "tallem"
version = "0.1.0"
description = "Topological Assembly from Local Euclidean Models"
authors = ["Matt Piekenbrock <matt.piekenbrock@gmail.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.9.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools>=42", "wheel", "numpy>=1.7.0", "pybind11~=2.6.1", "scikit-build", "cmake", "ninja"]
# build-backend = "poetry.core.masonry.api"
build-backend = "setuptools.build_meta"