## TALLEM project requirements doc
#[metadata]
[build-system]
requires = ["setuptools>=42", "wheel", "PythonExtensions", "poetry_core>=1.0.0", "meson>=0.59.0", "ninja"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "tallem"
version = "0.1.3"
description = "Topological Assembly of Locally Euclidean Models"
license = "Apache-2.0"
authors = ["Matt Piekenbrock <matt.piekenbrock@gmail.com>"]
readme = "README.md"
repository = "https://github.com/peekxc/tallem"
classifiers = [
	"Development Status :: 3 - Alpha", 
	"License :: OSI Approved :: Apache Software License", 
	"Operating System :: OS Independent",
	"Programming Language :: Python :: 3",
	"Intended Audience :: Science/Research"
]
build = "build.py"
packages = [
	{ include = "tallem", from = "src" }, # from = "src/tallem" 
]
include = [
	{ path = "src/**/*.so", format = "wheel" },
	"README.md"
] # TODO: configure this to add/remove things


[tool.poetry.dependencies]
python = "^3.8"
build = "^0.7.0"
wheel = "^0.37.0"
meson = "^0.59"
ninja = "^1.10.2"
Pillow = "^8.3.2"
pybind11 = "^2.8.0"
numpy = "^1.1"
scipy = "^1.6"
autograd = {version = "^1.3", optional = true}
pymanopt = {version = "^0.2.5", optional = true}
scikit-learn = {version = "^1.0", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^3.4"

# scripts as: package.submodule:function
# [tool.poetry.scripts]

## Original requirements manually compiled from the list generated by " pipdeptree | grep -e '^\S' " specified in the src/tallem directory 
[tool.poetry.extras]
autograd = ["autograd"]
pymanopt = ["pymanopt"]
sklearn = ["sklearn"]
