/* Generated by Cython 0.29.24 */

#ifndef __PYX_HAVE__tallem__extensions__mds_cython
#define __PYX_HAVE__tallem__extensions__mds_cython

#include "Python.h"

#ifndef __PYX_HAVE_API__tallem__extensions__mds_cython

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C void cython_dsyevr_cpp(double *, double *, double *, int, int, int, double);
__PYX_EXTERN_C void _dyevr(__Pyx_memviewslice, int, int, double, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice);
__PYX_EXTERN_C PyObject *cython_dsyevr(PyObject *, PyObject *, PyObject *, double, PyObject *, int __pyx_skip_dispatch);

#endif /* !__PYX_HAVE_API__tallem__extensions__mds_cython */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initmds_cython(void);
#else
PyMODINIT_FUNC PyInit_mds_cython(void);
#endif

#endif /* !__PYX_HAVE__tallem__extensions__mds_cython */
