name: "Build distribution"
on: [push, workflow_dispatch]
jobs: 
  build_ciwheels: 
    env: 
      CIBW_ARCHS_LINUX: x86_64
      CIBW_BUILD: cp38-manylinux_x86_64
      CIBW_BUILD_FRONTEND: pip
      CIBW_BUILD_VERBOSITY: 1
      CIBW_TEST_COMMAND: "pytest {project}/tests"
      CIBW_TEST_REQUIRES: pytest
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: jwlawson/actions-setup-cmake@v1.9
        with: 
          cmake-version: 3.16.x
      - run: |
            python -m pip install --upgrade pip
            pip install build
      - uses: pypa/cibuildwheel@v1.12.0
      - uses: actions/upload-artifact@v2
        with: 
          path: ./wheelhouse/*.whl
  build_ubuntu: 
    runs-on: ubuntu-latest
    steps: 
      - run: "cat /etc/os-release"
      - uses: actions/checkout@v2
      - run: "python -m pip install --upgrade pip"
      - uses: actions/setup-python@v2
        with: 
          architecture: x64
          python-version: 3.9
      - name: "Setup linux APT dependencies"
        run: |
            sudo apt-get update
            apt-get install gcc openssl bzip2 libffi-dev libhdf5-dev
            apt-get install --yes python3-dev
            apt-get install --yes python3 python3-pip python3-setuptools python3-wheel ninja-build
            apt install --yes --no-install-recommends ninja-build gfortran liblapack-dev liblapacke-dev
            pip install --upgrade pip
      - name: "Setup cmake"
        uses: jwlawson/actions-setup-cmake@v1.9
        with: 
          cmake-version: 3.16.x
      - name: "Install Poetry Action"
        uses: snok/install-poetry@v1.2.1
      - name: "Poetry install"
        run: "poetry install -vvv"
      - name: "Build package with pip"
        run: "pip install ."
      - name: "Run tests with pytest"
        run: |
            sudo -H pip install pytest
            pip install pytest
            python -m pip install pytest 
            pytest tests/
  debian_docker: 
    container: dockcross/linux-x64
    runs-on: ubuntu-latest
    steps: 
      - run: "cat /etc/os-release"
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: 
          architecture: x64
          python-version: 3.9
      - run: |
            apt-get update
            apt-get install --yes gcc openssl bzip2 libffi-dev libhdf5-dev
            apt-get install --yes libblas-dev liblapack-dev gfortran 
            apt-get install --yes python3 python3-pip python3-setuptools python3-wheel
            apt-get install --yes python3-dev cmake meson ninja-build
            python -m pip install --upgrade pip
            pip install pytest
      - run: "pip install tallem"
      - run: "pytest tests/"
      - uses: actions/upload-artifact@v2
        with: 
          path: ./dist/tallem-*.whl
  centos_docker: 
    container: dockcross/manylinux2014-x64
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/setup-python@v2
        with: 
          architecture: x64
          python-version: 3.9
      - run: |
          yum install gcc openssl-devel bzip2-devel libffi-devel hdf5 -y
          yum install blas blas-devel lapack lapack-devel -y
          cd ~ && python3.8 -m venv . && source bin/activate
          python -m pip install --upgrade pip
      - uses: actions/checkout@v2
      - run: "ls"
      - run: "pip install tallem"
      - run: "pytest tests/"
      - uses: actions/upload-artifact@v2
        with: 
          path: ./dist/tallem-*.whl
