name: Build distribution

on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    runs-on: "ubuntu-latest" # ${{ matrix.os }}
    # strategy:
    #   fail-fast: true
    #   matrix:
    #     os: ["ubuntu-latest"] # "windows-latest", "macos-latest"
    #     python-version: ["3.9"] #"3.7", "3.8", 

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 # ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: python -m pip install --upgrade pip

      - name: Install Setuptools, build, and wheel
        run: pip install setuptools build wheel

      - name: Install Pillow 
        run: pip install Pillow

      - name: Install PythonExtensions 
        run: pip install PythonExtensions

      - name: Install meson + ninja 
        run: pip install meson ninja  

      - name: Install numpy
        run: pip install numpy 

      - name: Install Pybind 11
        run: pip install "pybind11[global]"

      - name: Install SciPy
        run: pip install scipy

      - name: Install pytest
        run: pip install pytest 

      # - name: Cache dependencies
      #   uses: actions/cache@v2.1.6

      - name: Build extension modules 
        run: meson build

      - name: Build package 
        run: python -m build --wheel --outdir .

      - name: Install Package
        run: pip install -e .

      - name: Run tests
        run: pytest