name: Build distribution

on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    runs-on: "ubuntu-latest" # ${{ matrix.os }}
    # strategy:
    #   fail-fast: true
    #   matrix:
    #     os: ["ubuntu-latest"] # "windows-latest", "macos-latest"
    #     python-version: ["3.9"] #"3.7", "3.8", 

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 # ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: python -m pip install --upgrade pip

      # - name: Cache dependencies
      #   uses: actions/cache@v2.1.6

      - name: Install Package
        run: pip install -e .

      - name: Run tests
        run: pytest